# for module compiling
import os
Import('RTT_ROOT')
from building import *

cwd     = GetCurrentDir()
path    = [cwd]
src     = Glob('*.c')

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path)

cwd = GetCurrentDir()
objs = [group]
list = os.listdir(cwd)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
